package io.github.karan.mbus.views;

import android.content.Intent;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.ListView;
import android.widget.Spinner;

import java.util.ArrayList;
import java.util.Collections;

import io.github.karan.mbus.R;
import io.github.karan.mbus.controllers.PriceComparator;
import io.github.karan.mbus.controllers.TimeComparator;
import io.github.karan.mbus.models.Bus;

public class mBus_AvailableBusesActivity extends AppCompatActivity implements AdapterView.OnItemSelectedListener {

    ArrayList<String> listItems = new ArrayList<>();
    ArrayAdapter<String> adapter;

    ArrayList<Bus> pleasantonBuses;
    /**
     * This is the default method generated by Android Studio.
     * It sets the layout to Bus List Activity,
     * initializes and populates Spinner menu of options for sorting,
     * creates Bus objects and store them into array lists,
     * extracts the information in bundle passed from MainActivity and store into current activity.
     **/
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_m_bus__available_buses);

        //Create Spinner
        Spinner spinMe =  findViewById( R.id.spinner1);
        final ListView list =  findViewById(R.id.list);
        adapter = new ArrayAdapter<>(this, android.R.layout.simple_list_item_1,listItems);

        list.destroyDrawingCache();
        list.setVisibility(ListView.INVISIBLE);
        list.setVisibility(ListView.VISIBLE);

        list.setAdapter(adapter);
        spinMe.setOnItemSelectedListener(this);
        String[] categories = new String[]{"Price", "Time"};

        ArrayAdapter<String> myAdapt = new ArrayAdapter<>(this, android.R.layout.simple_spinner_item, categories);

        myAdapt.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);

        generateDummyData();

        spinMe.setAdapter(myAdapt);

    }

    public void onItemSelected(AdapterView<?> parent, View view, int position, long id) {
        String item = parent.getSelectedItem().toString();
        switch (item) {
            case "Price": // sort by price
                adapter.clear();
                Collections.sort(pleasantonBuses, new PriceComparator());
                displayPleasantonBusList();
                break;

            case "Time": //sort by time
                adapter.clear();
                Collections.sort(pleasantonBuses, new TimeComparator());
                displayPleasantonBusList();
        }
    }

    public void displayPleasantonBusList() {
        int i = pleasantonBuses.size();
        for(int j=0; j< i; j++)
        {
            Bus a = pleasantonBuses.get(j);
            listItems.add(a.toString());
        }

    }

    @Override
    public void onNothingSelected(AdapterView<?> parent) {

    }

    private void generateDummyData() {
        pleasantonBuses = new ArrayList<>();
        pleasantonBuses.add(new Bus (5L, "San Jose", "Pleasanton",
                "5:00PM","6:44PM",2, 87));
        pleasantonBuses.add(new Bus (3L,"Santa Clara", "Pleasanton",
                "12:00PM", "1:17PM", 5, 44));
        pleasantonBuses.add(new Bus (1L, "San Jose", "Pleasanton",
                "5:00AM","7:44AM",1, 120));
        pleasantonBuses.add(new Bus (2L,"Santa Clara", "Pleasanton",
                "1:00PM", "2:22PM", 9, 23));
        pleasantonBuses.add(new Bus (4L, "San Francisco", "Pleasanton",
                "4:00PM","6:44PM",14, 13));
        pleasantonBuses.add(new Bus (6L,"Santa Clarita", "Pleasanton",
                "9:00AM", "11:01AM", 1, 101));
    }

    public void onBackPressed() {
        super.onBackPressed();

        Intent intent = new Intent(this, mBus_HomeActivity.class);
        startActivity(intent);
        finish();

    }

}
